- README.md
Ref https://github.com/fredrikekre/Runic.jl/commit/e7229cb65e28067c52cd16f8566f714e87cf6955#commitcomment-144509528 cc @klafyvel
> Refine installation and editor integration docs

- README.md
As it was, the proposed git hook will fail if no Julia file has been edited in the commit (for example if we only edited Project.toml).
> fix(readme): Add a test for empty file list in git hook.

- src/runestone.jl
This is kind of sad...
```
code_warntype(Runic.spaces_in_listlike, Tuple{Runic.Context, Runic.Node})
```
showed that 
```
require_trailing_comma::Core.Box
last_item_idx::Core.Box
```
and this poisoned a bunch of other values they touch to become `::Any`.
For verifying the formatting of `base/*` in the julia repo:
Before:
```
1.793848 seconds (42.09 M allocations: 1.342 GiB, 3.55% gc time)
```
After:
```
1.576102 seconds (26.10 M allocations: 1.068 GiB, 3.58% gc time)
```
The times are kind of variable because it hits the filesystem quite a lot but it allocates around half at least.
> avoid variables captured in closure from becoming boxed by passing them in as arguments.

- README.md
- src/Runic.jl
- test/runtests.jl
This patch implements `# runic: on` and `# runic: off` toggle comments that can be included in the source to toggle formatting on/off.
The two comments i) must be placed on their own lines, ii) must be on the same level in the expression tree, and iii) must come in pairs. An exception to condition iii) is made for top level toggle comments so that formatting for a whole file can be disabled by a `# runic: off` comment at the top without having to add one also at the end of the file.
For compatibility with JuliaFormatter, `#! format: (on|off)` is also
supported but it is not possible to pair e.g. a `# runic: off` comment
with a `#! format: on` comment.
Closes #12, closes #41.
> Implement `# runic: (off|on)` toggle comments

- src/chisels.jl
- src/runestone.jl
- test/runtests.jl
This patch reworks the indentation after assignment. For "blocklike" (try/if/triple strings) right hand sides the indentation is disabled. Superfluous newlines are removed. For example
```julia
x =
if a
x
else
y
end
```
will become
```julia
x = if a
x
else
y
end
```
A valid alternative is
```julia
x = if a
x
else
y
end
```
This highlights the start/end of the right hand side of the assignment in a better way, but it doesn't look very nice and this style is never really seen in the wild. For triple strings I think it is OK though, e.g.
```julia
x = """
foo
bar
"""
```
vs the current (and seen more in the wild)
```julia
x = """
foo
bar
"""
```
Closes #39.
> Rework indentation after assignment

- src/chisels.jl
- src/runestone.jl
- test/runtests.jl
This patch introduces line continuation based indent for triple strings,
which typically span multiple lines without any explicit newlines in the
syntax tree (since they are hidden inside the string).
This result in the following changes, some of which are clearly
bugfixes:
Operator chains:
```diff
"""
abc
""" * """
-def
-"""
+    def
+    """
```
Operator chain as assignment right hand side:
```diff
x = """
-abc
-""" * """
-def
-"""
+    abc
+    """ * """
+    def
+    """
```
Implicit tuples:
```diff
"""
abc
""",
"""
-def
-"""
+    def
+    """
```
Note that single triple strings as a right hand side is excluded from
the indent rule, similar to having `if/try/let/...` blocks as a right
hand side.
> Line continuation indent for triple-strings

- src/Runic.jl
- src/runestone.jl
- test/runtests.jl
This patch removes trailing semicolons in blocklike contexts (`for`, `if`, ...). Semicolons are left alone in top level contexts since they are sometimes used there for output suppression (e.g. Documenter examples or scripts that are copy-pasted/included in the REPL).
Semicolons before comments are replaced with a single space instead of removed so that if the comments are aligned before, they will be aligned after, for example
```julia
begin
x = 1; # This is x
y = 2  # This is y
end
```
will become
```julia
begin
x = 1  # This is x
y = 2  # This is y
end
```
> Drop trailing semicolons in block contexts

- README.md
- src/runestone.jl
- test/runtests.jl
This patch adds trimming of trailing whitespace inside of comments in addition to the trimming of trailing whitespace in code. Note that trailing whitespace inside of multiline is not trimmed since doing so would change the content of the string.
Closes #50.
> Trim trailing whitespace in comments

- src/Runic.jl
- src/runestone.jl
- test/runtests.jl
> Ensure at least one space before comments

- src/runestone.jl
- test/runtests.jl
This patch fixes the usage of trailing commas in implicit tuples when used in destructuring assignment, e.g. `x, = z`. In this context the trailing comma is needed to preserve the tuple node, which is different from e.g. implicit tuples in `do`-blocks. A trailing comma is allowed (e.g. preserved from the source) for multi-item implicit tuples so that e.g. `x, y, = z` can be used to signal that z contains more than two items. Closes #58.
> Fix trailing comma in implicit tuples in destructuring

- src/chisels.jl
- src/runestone.jl
- test/runtests.jl
This patch changes where spaces are inserted before comments so that it is always added as a sibling to the comment instead of as a "uncle" when a comment is found as the first leaf of a kid.
> Fix insertion of space before comment

- README.md
- src/JuliaSyntax.jl
- src/Runic.jl
- src/ToggleableAsserts.jl
- src/chisels.jl
- src/debug.jl
- src/main.jl
- src/runestone.jl
- test/runtests.jl
This patch make sure that function definitions end with an explicit `return` statement before the last expression in the body.
If `for` or `while` is the last expression a `return nothing` node is inserted after the loop instead of `return for ...`.
`if`, `try`, `let`, and `begin` are currently are left as they are. Perhaps in the future Runic will recurse down into branches, or insert `return if` but for now this is left alone.
Another exception is also made whenever the last expression is a call to `throw` or `error` because it is pretty clear that the function will not return in this case (`return throw(...)` look silly).
Closes #43.
> Insert explicit return expressions in functions/macros/do-blocks

- src/Runic.jl
This doesn't cost much (5 % perf hit for some large files) and can catch some errors. Note that it isn't possible/trivial to compare the trees since the formatter make changes to it.
> Verify that Runic's output is parseable

- README.md
- src/runestone.jl
- test/runtests.jl
`..` is typically used similarly to `:` which is already excluded from the space-around-operator rule.
> Don't use spaces around `..`

- src/runestone.jl
- test/runtests.jl
This patch fixes single space before `return`, `local`, `global`, and `const`. Fixes #76.
> Ensure single space before more keywords

- README.md
- src/Runic.jl
- test/runtests.jl
This patch relaxes the toggle comments `# runic: (off|on)` such that the comment may contain more than just the toggle comment. This is useful when combining with other "pragmas" such as e.g. Literate.jl line filters. For example, the following now also toggles formatting:
```julia
not = formatted   #src
```
> Relax toggle comments to allow more "pragmas"

- README.md
- src/runestone.jl
- test/runtests.jl
Behavior of `..` is more tricky than `:`. Sometimes the space is
required like in e.g. `a .. -b` which, formatted as `a..-b`, would give
`ParseError: invalid operator ..-`.
This reverts commit 7d26dcf2687fc148e5cc038295351ef204e101e2.
> Revert "Don't use spaces around `..` (#74)"

- src/runestone.jl
- test/runtests.jl
Same issue as in #78, with same fix as in #83, but for a different
edgecase.
> Fix extra space in export/public/global/local multiline lists

- src/runestone.jl
- test/runtests.jl
This patch removes an assertion about whitespace after the `function`
keyword in the indent pass. The core issue is the
`is_longform_anon_function` predicate which is wrong for the testcases,
but the assert is not needed since we can just use the next
non-whitespace noce as the signature in all cases. Fixes #109.
> Fix bad assertion in function signatures

- CHANGELOG.md
- src/chisels.jl
- src/runestone.jl
- test/runtests.jl
Fix a bug that caused "single space after keyword" to not apply after the `function` keyword in non-standard function definitions.
> Consistently use single space after `function`

- CHANGELOG.md
- src/runestone.jl
- test/runtests.jl
This patch ensures that a single space is used also after `let` like other keywords.
> Fix multiple spaces after `let`

- CHANGELOG.md
- src/Runic.jl
- src/debug.jl
- src/main.jl
- test/maintests.jl
- test/runtests.jl
This patch implements the `--lines=a:b` command line argument for
limiting the formatting to the line range `a:b`. Multiple ranges are
supported. Close #114.
Examples:
```
$ cat main.jl
function f(a,b,c,d)
a  +  b  +  c  +  d
end
$ ./bin/runic --lines=1:1 main.jl
function f(a, b, c, d)
a  +  b  +  c  +  d
end
$ ./bin/runic --lines=2:2 main.jl
function f(a,b,c,d)
return a + b + c + d
end
```
> Support range formatting

- CHANGELOG.md
- src/main.jl
- test/maintests.jl
This patch improves the command line argument parsing to handle more
edge cases related to input files and directories (such as e.g. empty
directories).
> Improved command line argument parsing

- CHANGELOG.md
- src/main.jl
- test/maintests.jl
This patch simplifies the verbose output a bit and fixes various cases
where an error message would be printed before the file info line
instead of after.
> Simplify --verbose output

- README.md
- bin/git-runic
Adds the [`git-runic`](https://github.com/fredrikekre/Runic.jl/blob/master/bin/git-runic) script (a modified version of [`git-clang-format`](https://github.com/llvm/llvm-project/blob/main/clang/tools/clang-format/git-clang-format)) from https://github.com/fredrikekre/Runic.jl/pull/120#issuecomment-2522991937 to the repository.
> Add git-runic script

- CHANGELOG.md
- src/runestone.jl
- test/runtests.jl
Fix formatting of floating point literals that use `−` (Unicode U+2212)
instead of the typically used `-` (ASCII/Unicode U+002D). The parser
treats them as synonyms but the former triggered an assertion error in
Runic while formatting. After this change Runic will normalize to `-`
when formatting. Fixes #137.
> Fix formatting of negative floating point literals

- CHANGELOG.md
- Project.toml
- src/main.jl
- test/maintests.jl
> Remove range format markers when using --lines and --diff together

- README.md
closes #148 
The issue for me was installing was hitting a conflict with JuliaSyntax, which had been loaded by OhMyREPL in my startup in my main environment.
> ignore startup.jl to aid in avoiding dependency conflicts

- CHANGELOG.md
- Project.toml
- src/main.jl
- test/maintests.jl
This allows assuming a filename when formatting/checking data from stdin. This is used for error messages etc.
> New command line argument `--stdin-filename=<filename>`

- CHANGELOG.md
- Project.toml
- src/runestone.jl
- test/runtests.jl
Ohter number literals, like floats and integers, with underscores are already ignored (for now). Fixes #169.
> Ignore formatting of hex literals with underscores
